# Generated by Django 2.2.1 on 2021-01-26 18:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderHeader',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('import_date', models.DateField(blank=True, null=True)),
                ('app_id', models.CharField(max_length=255, unique=True)),
                ('status', models.CharField(max_length=255)),
                ('import_status', models.CharField(blank=True, max_length=255, null=True)),
                ('client_cgc', models.CharField(max_length=20)),
                ('seller_cgc', models.CharField(max_length=20)),
                ('payment_condition', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('operation_desc', models.CharField(blank=True, max_length=4000, null=True)),
                ('operation_technical_desc', models.CharField(blank=True, max_length=4000, null=True)),
                ('unique', models.CharField(max_length=12)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'order_header',
            },
        ),
        migrations.CreateModel(
            name='OrderItems',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('company', models.CharField(max_length=2)),
                ('branch', models.CharField(max_length=2)),
                ('description', models.CharField(max_length=255)),
                ('product', models.CharField(max_length=6)),
                ('promotional', models.CharField(max_length=255)),
                ('fixed_price', models.BooleanField()),
                ('quantity', models.FloatField()),
                ('discount', models.FloatField()),
                ('original_price', models.FloatField()),
                ('price', models.FloatField()),
                ('total', models.FloatField()),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('lot', models.CharField(max_length=255)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.OrderHeader')),
            ],
            options={
                'db_table': 'order_items',
            },
        ),
    ]
